edition = "2024"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity="Module"
max_width = 72
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
